### PR TITLE
try using CloudHole

### PR DESCRIPTION
**Pull request by scakemyer**

### CODE REVIEW

**Comment by mancuniancol** [comment]
thank you. I will do some changes,though.  Because, I want to keep magnetic independent of Quasar. 

Btw, where can the users to get the cloudhole key?  I want to add that to my documentation

**Comment by scakemyer** [comment]
The CloudHole key is generated server-side by the API based on the user's IP and a secret token. Users get it from the Firefox add-on (also works in Chrome). I understand you want to keep it independent, but if you add a setting for the key, users would have to enter it in both places. A better way is just to query https://cloudhole.herokuapp.com/key which I'll also do in Quasar, adding an enable/disable setting instead.

**Comment by mancuniancol** [comment]
I wasn't sure how the API worked. Now, it is clearer. I will do that query instead. From magnetic service to avoid multiple request for the same key.

**Comment by scakemyer** [comment]
Sounds good. I'd also recommend you do the same for clearances, since it's currently making at least one request to https://cloudhole.herokuapp.com/clearances for each provider.

**Comment by mancuniancol** [comment]
Yes. I will that. I don't want to compromise the performance doing useless requests. 
I am going to clean the code too. There are old things that I don't use anymore.

**Pull request merged**
